      SUBROUTINE CAUCHY_DAXPY(N, A, X, Y) BIND(C,
     &     NAME="cauchy_daxpy")
      USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT, C_DOUBLE
      IMPLICIT NONE
      INTEGER(C_INT), VALUE, INTENT(IN) :: N
      REAL(C_DOUBLE), VALUE, INTENT(IN) :: A
      REAL(C_DOUBLE), INTENT(IN) :: X(*)
      REAL(C_DOUBLE), INTENT(INOUT) :: Y(*)
      INTEGER(C_INT) :: INCX, INCY
      EXTERNAL DAXPY

      INCX = 1
      INCY = 1
      CALL DAXPY(N, A, X, INCX, Y, INCY)
      END SUBROUTINE CAUCHY_DAXPY
