      SUBROUTINE CAUCHY_FORTRAN_EVALUATE(SOURCE, SOURCE_LEN,
     &     X, X_LEN, ANSWER, INFO) BIND(C,
     &     NAME="cauchy_fortran_evaluate_math_expr")
      USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_CHAR, C_INT,
     &     C_DOUBLE
      IMPLICIT NONE

      CHARACTER(KIND=C_CHAR), INTENT(IN) :: SOURCE(*)
      INTEGER(C_INT), VALUE, INTENT(IN) :: SOURCE_LEN
      REAL(C_DOUBLE), INTENT(IN) :: X(*)
      INTEGER(C_INT), VALUE, INTENT(IN) :: X_LEN
      REAL(C_DOUBLE), INTENT(OUT) :: ANSWER
      INTEGER(C_INT), INTENT(OUT) :: INFO
      INTEGER(C_INT) :: I
      CHARACTER(KIND=C_CHAR, LEN=SOURCE_LEN) :: SOURCE_TEXT

      INTERFACE
         FUNCTION RUST_EVALUATE(SOURCE, SOURCE_LEN, X, X_LEN,
     &        ANSWER) RESULT(STATUS) BIND(C,
     &        NAME="cauchy_evaluate_math_expr")
         USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_CHAR, C_INT,
     &        C_DOUBLE

         CHARACTER(KIND=C_CHAR), INTENT(IN) :: SOURCE(*)
         INTEGER(C_INT), VALUE, INTENT(IN) :: SOURCE_LEN
         REAL(C_DOUBLE), INTENT(IN) :: X(*)
         INTEGER(C_INT), VALUE, INTENT(IN) :: X_LEN
         REAL(C_DOUBLE), INTENT(OUT) :: ANSWER
         INTEGER(C_INT) :: STATUS
         END FUNCTION RUST_EVALUATE
      END INTERFACE

      DO 10 I = 1, SOURCE_LEN
         SOURCE_TEXT(I:I) = SOURCE(I)
   10 CONTINUE

      INFO = RUST_EVALUATE(SOURCE, SOURCE_LEN, X, X_LEN,
     &   ANSWER)
           WRITE (*, *) 'RUST_EVALUATE: SOURCE="', SOURCE_TEXT,
     &     '" SOURCE_LEN=', SOURCE_LEN, ' X=', X(1),
     &     ' ANSWER=', ANSWER
      END SUBROUTINE CAUCHY_FORTRAN_EVALUATE
