      SUBROUTINE CAUCHY_ODE_FORTRAN_EVALUATE(SOURCE, SOURCE_LEN,
     &     X, X_LEN, ANSWER, INFO) BIND(C,
     &     NAME="cauchy_ode_fortran_evaluate_math_expr")
      USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_CHAR, C_INT,
     &     C_DOUBLE
      IMPLICIT NONE

      CHARACTER(KIND=C_CHAR), INTENT(IN) :: SOURCE(*)
      INTEGER(C_INT), VALUE, INTENT(IN) :: SOURCE_LEN
      REAL(C_DOUBLE), INTENT(IN) :: X(*)
      INTEGER(C_INT), VALUE, INTENT(IN) :: X_LEN
      REAL(C_DOUBLE), INTENT(OUT) :: ANSWER
      INTEGER(C_INT), INTENT(OUT) :: INFO

      INTERFACE
         FUNCTION RUST_EVALUATE(SOURCE, SOURCE_LEN, X, X_LEN,
     &        ANSWER) RESULT(STATUS) BIND(C,
     &        NAME="cauchy_ode_evaluate_math_expr")
         USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_CHAR, C_INT,
     &        C_DOUBLE

         CHARACTER(KIND=C_CHAR), INTENT(IN) :: SOURCE(*)
         INTEGER(C_INT), VALUE, INTENT(IN) :: SOURCE_LEN
         REAL(C_DOUBLE), INTENT(IN) :: X(*)
         INTEGER(C_INT), VALUE, INTENT(IN) :: X_LEN
         REAL(C_DOUBLE), INTENT(OUT) :: ANSWER
         INTEGER(C_INT) :: STATUS
         END FUNCTION RUST_EVALUATE
      END INTERFACE

      INFO = RUST_EVALUATE(SOURCE, SOURCE_LEN, X, X_LEN,
     &   ANSWER)
      END SUBROUTINE CAUCHY_ODE_FORTRAN_EVALUATE
